controllers:
    resource: ../src/Controller/
    type: annotation
kernel:
    resource: ../src/Kernel.php
    type: annotation
api_login:
    path: /login
    methods: ['POST']
api_logout:
    path: /logout
    methods: ['GET']
